// Code generated by goctl. DO NOT EDIT.
// Source: payment.proto

package payment

import (
	"context"

	"zero-shop/payment/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetPaymentDetailReq  = pb.GetPaymentDetailReq
	GetPaymentDetailResp = pb.GetPaymentDetailResp
	OrderPaymentReq      = pb.OrderPaymentReq
	OrderPaymentResp     = pb.OrderPaymentResp

	Payment interface {
		OrderPayment(ctx context.Context, in *OrderPaymentReq, opts ...grpc.CallOption) (*OrderPaymentResp, error)
		GetPaymentDetail(ctx context.Context, in *GetPaymentDetailReq, opts ...grpc.CallOption) (*GetPaymentDetailResp, error)
	}

	defaultPayment struct {
		cli zrpc.Client
	}
)

func NewPayment(cli zrpc.Client) Payment {
	return &defaultPayment{
		cli: cli,
	}
}

func (m *defaultPayment) OrderPayment(ctx context.Context, in *OrderPaymentReq, opts ...grpc.CallOption) (*OrderPaymentResp, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.OrderPayment(ctx, in, opts...)
}

func (m *defaultPayment) GetPaymentDetail(ctx context.Context, in *GetPaymentDetailReq, opts ...grpc.CallOption) (*GetPaymentDetailResp, error) {
	client := pb.NewPaymentClient(m.cli.Conn())
	return client.GetPaymentDetail(ctx, in, opts...)
}
