// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	commonProduct "zero-shop/product/api/internal/handler/commonProduct"
	seckillProduct "zero-shop/product/api/internal/handler/seckillProduct"
	storeProduct "zero-shop/product/api/internal/handler/storeProduct"
	userProduct "zero-shop/product/api/internal/handler/userProduct"
	"zero-shop/product/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/homepage/carousel",
				Handler: commonProduct.CarouselHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/homepage/categorylist",
				Handler: commonProduct.CategoryListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/homepage/recommend",
				Handler: commonProduct.RecommendHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/homepage/search",
				Handler: commonProduct.SearchProductHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/product/category",
				Handler: commonProduct.CategoryProductListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/product/detail",
				Handler: commonProduct.ProductDetailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/product/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CheckStoreState},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/store/product",
					Handler: storeProduct.CreateProductHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/store/shelf",
					Handler: storeProduct.ShelfProductHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/store/product",
					Handler: storeProduct.UpdateProductHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/store/soldout",
					Handler: storeProduct.SoldoutProductHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/store/product",
					Handler: storeProduct.DeleteProductHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/store/seckill",
					Handler: storeProduct.CreateSeckillHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/store/seckill",
					Handler: storeProduct.DeleteSeckillHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/product/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CheckUserState},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/collect/product",
					Handler: userProduct.CreateCollectProductHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/collect/product",
					Handler: userProduct.CollectProductListHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/collect/product",
					Handler: userProduct.DeleteCollectProductHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/product/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/seckill/list",
				Handler: seckillProduct.SeckillListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/seckill/detail",
				Handler: seckillProduct.SeckillDetailHandler(serverCtx),
			},
		},
		rest.WithPrefix("/product/v1"),
	)
}
