// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCart = "cart"

// Cart mapped from table <cart>
type Cart struct {
	ID         int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	CreateTime time.Time `gorm:"column:create_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
	DeleteTime time.Time `gorm:"column:delete_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"delete_time"`
	DelState   int64     `gorm:"column:del_state;type:tinyint;not null" json:"del_state"`
	UserID     int64     `gorm:"column:user_id;type:bigint;not null;index:ix_user_id,priority:1" json:"user_id"`
	ProductID  int64     `gorm:"column:product_id;type:bigint;not null;index:ix_product_id,priority:1" json:"product_id"`
	Count      int64     `gorm:"column:count;type:int;not null;default:1;comment:数量" json:"count"`
	Checked    int64     `gorm:"column:checked;type:tinyint(1);not null;comment:是否勾选：1-已勾选，0-未勾选" json:"checked"`
}

// TableName Cart's table name
func (*Cart) TableName() string {
	return TableNameCart
}
