// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOrder = "order"

// Order mapped from table <order>
type Order struct {
	ID             int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	CreateTime     time.Time `gorm:"column:create_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime     time.Time `gorm:"column:update_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
	DeleteTime     time.Time `gorm:"column:delete_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"delete_time"`
	DelState       int64     `gorm:"column:del_state;type:tinyint;not null" json:"del_state"`
	Version        int64     `gorm:"column:version;type:bigint;not null;comment:乐观锁版本号" json:"version"`
	OrderSn        string    `gorm:"column:order_sn;type:varchar(25);not null;uniqueIndex:ix_order_sn,priority:1;comment:订单号" json:"order_sn"`
	UserID         int64     `gorm:"column:user_id;type:bigint;not null;index:ix_user_id,priority:1" json:"user_id"`
	UserAddressID  int64     `gorm:"column:user_address_id;type:bigint;not null;comment:用户收货表id" json:"user_address_id"`
	ProductID      int64     `gorm:"column:product_id;type:bigint;not null;index:ix_product_id,priority:1;comment:商品id" json:"product_id"`
	SeckillID      int64     `gorm:"column:seckill_id;type:bigint;not null;comment:秒杀商品id，如果为普通商品，该字段为0" json:"seckill_id"`
	ProductStoreID int64     `gorm:"column:product_store_id;type:bigint;not null;comment:商品店铺id" json:"product_store_id"`
	ProductBossID  int64     `gorm:"column:product_boss_id;type:bigint;not null;comment:商品店主id" json:"product_boss_id"`
	ProductCount   int64     `gorm:"column:product_count;type:int unsigned;not null;default:1;comment:购买的商品数量" json:"product_count"`
	UnitPrice      int64     `gorm:"column:unit_price;type:bigint;not null;comment:商品单价（分）" json:"unit_price"`
	TotalPrice     int64     `gorm:"column:total_price;type:bigint;not null;comment:支付金额（分）" json:"total_price"`
	Status         int64     `gorm:"column:status;type:int;not null;comment:订单状态：-1-已取消，10-未付款，20-已付款，30-待发货，40-待收货，50-交易成功，60-交易关闭" json:"status"`
	Remark         string    `gorm:"column:remark;type:varchar(64);not null;comment:用户下单备注" json:"remark"`
}

// TableName Order's table name
func (*Order) TableName() string {
	return TableNameOrder
}
