// Code generated by goctl. DO NOT EDIT.
package types

type CartProduct struct {
	ID            int64  `json:"id"`
	ProductID     int64  `json:"productId"`
	Title         string `json:"title"`
	Banner        string `json:"banner"`
	Price         int64  `json:"price"`
	DiscountPrice int64  `json:"discountPrice"`
	Count         int64  `json:"count"`
	Checked       int64  `json:"checked"`
}

type AddProductToCartReq struct {
	ProductID int64 `json:"productId"`
	Count     int64 `json:"count"`
}

type CartProductListResp struct {
	CartProducts []CartProduct `json:"cartProducts"`
}

type DeteleProductFromCartReq struct {
	CartID int64 `json:"cartId"`
}

type UpdateProductDetailReq struct {
	CartID int64 `json:"cartId"`
	Count  int64 `json:"count"`
	Check  int64 `json:"check"`
}
