// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePayment = "payment"

// Payment mapped from table <payment>
type Payment struct {
	ID             int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	CreateTime     time.Time `gorm:"column:create_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime     time.Time `gorm:"column:update_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
	DeleteTime     time.Time `gorm:"column:delete_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"delete_time"`
	DelState       int64     `gorm:"column:del_state;type:tinyint;not null" json:"del_state"`
	Version        int64     `gorm:"column:version;type:bigint;not null;comment:乐观锁版本号" json:"version"`
	PaymentSn      string    `gorm:"column:payment_sn;type:varchar(25);not null;uniqueIndex:ix_payment_sn,priority:1;comment:支付流水单号" json:"payment_sn"`
	OrderSn        string    `gorm:"column:order_sn;type:varchar(25);not null;uniqueIndex:ix_order_sn,priority:1;comment:订单号" json:"order_sn"`
	UserID         int64     `gorm:"column:user_id;type:bigint;not null" json:"user_id"`
	PayMode        int64     `gorm:"column:pay_mode;type:tinyint(1);not null;comment:支付方式：1-平台钱包支付，2-微信支付，3-支付宝支付" json:"pay_mode"`
	TradeType      string    `gorm:"column:trade_type;type:varchar(20);not null;comment:第三方支付类型" json:"trade_type"`
	TradeState     string    `gorm:"column:trade_state;type:varchar(20);not null;comment:第三方支付状态" json:"trade_state"`
	PayTotal       int64     `gorm:"column:pay_total;type:bigint;not null;comment:支付总金额（分）" json:"pay_total"`
	TransactionID  string    `gorm:"column:transaction_id;type:char(32);not null;comment:第三方支付单号" json:"transaction_id"`
	TradeStateDesc string    `gorm:"column:trade_state_desc;type:varchar(256);not null;comment:支付状态描述" json:"trade_state_desc"`
	PayStatus      int64     `gorm:"column:pay_status;type:tinyint(1);not null;comment:交易状态：-1-支付失败；0-未支付；1-支付成功；2-已退款" json:"pay_status"`
	PayTime        time.Time `gorm:"column:pay_time;type:datetime;not null;default:1970-01-01 08:00:00;comment:支付成功时间" json:"pay_time"`
}

// TableName Payment's table name
func (*Payment) TableName() string {
	return TableNamePayment
}
