// Code generated by goctl. DO NOT EDIT.
// Source: payment.proto

package server

import (
	"context"

	"zero-shop/payment/rpc/internal/logic"
	"zero-shop/payment/rpc/internal/svc"
	"zero-shop/payment/rpc/pb"
)

type PaymentServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedPaymentServer
}

func NewPaymentServer(svcCtx *svc.ServiceContext) *PaymentServer {
	return &PaymentServer{
		svcCtx: svcCtx,
	}
}

func (s *PaymentServer) OrderPayment(ctx context.Context, in *pb.OrderPaymentReq) (*pb.OrderPaymentResp, error) {
	l := logic.NewOrderPaymentLogic(ctx, s.svcCtx)
	return l.OrderPayment(in)
}

func (s *PaymentServer) GetPaymentDetail(ctx context.Context, in *pb.GetPaymentDetailReq) (*pb.GetPaymentDetailResp, error) {
	l := logic.NewGetPaymentDetailLogic(ctx, s.svcCtx)
	return l.GetPaymentDetail(in)
}
