// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID            int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	CreateTime    time.Time `gorm:"column:create_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime    time.Time `gorm:"column:update_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
	DeleteTime    time.Time `gorm:"column:delete_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"delete_time"`
	DelState      int64     `gorm:"column:del_state;type:tinyint;not null" json:"del_state"`
	Mobile        string    `gorm:"column:mobile;type:varchar(11);not null;uniqueIndex:ix_mobile,priority:1" json:"mobile"`
	Username      string    `gorm:"column:username;type:varchar(255);not null" json:"username"`
	Password      string    `gorm:"column:password;type:varchar(255);not null" json:"password"`
	Email         string    `gorm:"column:email;type:varchar(128);not null" json:"email"`
	Sex           int64     `gorm:"column:sex;type:tinyint(1);not null;comment:性别：1-男性，2-女性" json:"sex"`
	HeaderImageID int64     `gorm:"column:header_image_id;type:bigint;not null;comment:用户图像id" json:"header_image_id"`
	Signature     string    `gorm:"column:signature;type:text;not null;comment:个性签名" json:"signature"`
	Introduction  string    `gorm:"column:introduction;type:text;not null;comment:自我介绍" json:"introduction"`
	Money         int64     `gorm:"column:money;type:bigint;not null;comment:用户账户余额(单位：分)" json:"money"`
	SignStatus    int64     `gorm:"column:sign_status;type:tinyint(1);not null;default:1;comment:注册来源：1-网站注册，2-qq注册，3-微信注册" json:"sign_status"`
	Role          int64     `gorm:"column:role;type:tinyint(1);not null;default:1;comment:权限：-1-被禁用用户，1-普通用户,2-管理员" json:"role"`
	IsBoss        int64     `gorm:"column:is_boss;type:tinyint(1);not null;comment:是否为商家：0-不是，1-是" json:"is_boss"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
