// Code generated by goctl. DO NOT EDIT.
// Source: cart.proto

package cart

import (
	"context"

	"zero-shop/cart/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddProductToCartReq       = pb.AddProductToCartReq
	AddProductToCartResp      = pb.AddProductToCartResp
	CartProduct               = pb.CartProduct
	CartProductListReq        = pb.CartProductListReq
	CartProductListResp       = pb.CartProductListResp
	DeleteProductFromCartReq  = pb.DeleteProductFromCartReq
	DeleteProductFromCartResp = pb.DeleteProductFromCartResp
	UpdateProductDetailReq    = pb.UpdateProductDetailReq
	UpdateProductDetailResp   = pb.UpdateProductDetailResp

	Cart interface {
		AddProductToCart(ctx context.Context, in *AddProductToCartReq, opts ...grpc.CallOption) (*AddProductToCartResp, error)
		CartProductList(ctx context.Context, in *CartProductListReq, opts ...grpc.CallOption) (*CartProductListResp, error)
		DeleteProductFromCart(ctx context.Context, in *DeleteProductFromCartReq, opts ...grpc.CallOption) (*DeleteProductFromCartResp, error)
		UpdateProductDetail(ctx context.Context, in *UpdateProductDetailReq, opts ...grpc.CallOption) (*UpdateProductDetailResp, error)
	}

	defaultCart struct {
		cli zrpc.Client
	}
)

func NewCart(cli zrpc.Client) Cart {
	return &defaultCart{
		cli: cli,
	}
}

func (m *defaultCart) AddProductToCart(ctx context.Context, in *AddProductToCartReq, opts ...grpc.CallOption) (*AddProductToCartResp, error) {
	client := pb.NewCartClient(m.cli.Conn())
	return client.AddProductToCart(ctx, in, opts...)
}

func (m *defaultCart) CartProductList(ctx context.Context, in *CartProductListReq, opts ...grpc.CallOption) (*CartProductListResp, error) {
	client := pb.NewCartClient(m.cli.Conn())
	return client.CartProductList(ctx, in, opts...)
}

func (m *defaultCart) DeleteProductFromCart(ctx context.Context, in *DeleteProductFromCartReq, opts ...grpc.CallOption) (*DeleteProductFromCartResp, error) {
	client := pb.NewCartClient(m.cli.Conn())
	return client.DeleteProductFromCart(ctx, in, opts...)
}

func (m *defaultCart) UpdateProductDetail(ctx context.Context, in *UpdateProductDetailReq, opts ...grpc.CallOption) (*UpdateProductDetailResp, error) {
	client := pb.NewCartClient(m.cli.Conn())
	return client.UpdateProductDetail(ctx, in, opts...)
}
