// Code generated by goctl. DO NOT EDIT.
// Source: cart.proto

package server

import (
	"context"

	"zero-shop/cart/rpc/internal/logic"
	"zero-shop/cart/rpc/internal/svc"
	"zero-shop/cart/rpc/pb"
)

type CartServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedCartServer
}

func NewCartServer(svcCtx *svc.ServiceContext) *CartServer {
	return &CartServer{
		svcCtx: svcCtx,
	}
}

func (s *CartServer) AddProductToCart(ctx context.Context, in *pb.AddProductToCartReq) (*pb.AddProductToCartResp, error) {
	l := logic.NewAddProductToCartLogic(ctx, s.svcCtx)
	return l.AddProductToCart(in)
}

func (s *CartServer) CartProductList(ctx context.Context, in *pb.CartProductListReq) (*pb.CartProductListResp, error) {
	l := logic.NewCartProductListLogic(ctx, s.svcCtx)
	return l.CartProductList(in)
}

func (s *CartServer) DeleteProductFromCart(ctx context.Context, in *pb.DeleteProductFromCartReq) (*pb.DeleteProductFromCartResp, error) {
	l := logic.NewDeleteProductFromCartLogic(ctx, s.svcCtx)
	return l.DeleteProductFromCart(in)
}

func (s *CartServer) UpdateProductDetail(ctx context.Context, in *pb.UpdateProductDetailReq) (*pb.UpdateProductDetailResp, error) {
	l := logic.NewUpdateProductDetailLogic(ctx, s.svcCtx)
	return l.UpdateProductDetail(in)
}
