Name: product.rpc
ListenOn: 0.0.0.0:8082
Etcd:
  Hosts:
  - 127.0.0.1:2379
  Key: product.rpc

# log配置
Log:
  ServiceName: product-rpc
  Level: error

# 七牛云配置
Qiniu:
  AccessKey: AccessKey
  SecretKey: SecretKey
  Bucket: go-zero-shop-product
  CDN: http://rvx9qktl4.hn-bkt.clouddn.com/
  Zone: Zone
  Prefix: zero-shop

# Mysql配置
MysqlConf:
  DSN: root:123456@tcp(127.0.0.1:3306)/zero_shop_product?charset=utf8mb4&parseTime=True&loc=Local
# Redis配置
RedisConf:
  Addr: localhost:6379
  Password: 123456
  DB: 4
  PoolSize: 100

