// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCategory = "category"

// Category mapped from table <category>
type Category struct {
	ID         int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	CreateTime time.Time `gorm:"column:create_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
	DeleleTime time.Time `gorm:"column:delele_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"delele_time"`
	DelState   int64     `gorm:"column:del_state;type:tinyint;not null" json:"del_state"`
	Name       string    `gorm:"column:name;type:varchar(12);not null;comment:分类名称" json:"name"`
}

// TableName Category's table name
func (*Category) TableName() string {
	return TableNameCategory
}
