// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFavoriteProduct = "favorite_product"

// FavoriteProduct mapped from table <favorite_product>
type FavoriteProduct struct {
	ID           int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	CreateTime   time.Time `gorm:"column:create_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime   time.Time `gorm:"column:update_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
	DeleleTime   time.Time `gorm:"column:delele_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"delele_time"`
	DelState     int64     `gorm:"column:del_state;type:tinyint;not null" json:"del_state"`
	UserID       int64     `gorm:"column:user_id;type:bigint;not null;index:ix_user_id,priority:1" json:"user_id"`
	ProductID    int64     `gorm:"column:product_id;type:bigint;not null" json:"product_id"`
	ProductTitle string    `gorm:"column:product_title;type:varchar(32);not null" json:"product_title"`
	StoreID      int64     `gorm:"column:store_id;type:bigint;not null;comment:收藏商品店铺id" json:"store_id"`
}

// TableName FavoriteProduct's table name
func (*FavoriteProduct) TableName() string {
	return TableNameFavoriteProduct
}
