// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProductComment = "product_comment"

// ProductComment mapped from table <product_comment>
type ProductComment struct {
	ID         int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	CreateTime time.Time `gorm:"column:create_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
	DeleleTime time.Time `gorm:"column:delele_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"delele_time"`
	DelState   int64     `gorm:"column:del_state;type:tinyint;not null" json:"del_state"`
	UserID     int64     `gorm:"column:user_id;type:bigint;not null;index:ix_user_id,priority:1" json:"user_id"`
	ProductID  int64     `gorm:"column:product_id;type:bigint;not null;index:ix_product_id,priority:1" json:"product_id"`
	IsGood     int64     `gorm:"column:is_good;type:tinyint(1);not null;comment:-1-差评，0-中性，1-好评" json:"is_good"`
	Content    string    `gorm:"column:content;type:text;not null;comment:评论内容" json:"content"`
	AddContent string    `gorm:"column:add_content;type:varchar(1024);not null;comment:追加评论内容" json:"add_content"`
}

// TableName ProductComment's table name
func (*ProductComment) TableName() string {
	return TableNameProductComment
}
