// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProductImg = "product_img"

// ProductImg mapped from table <product_img>
type ProductImg struct {
	ID         int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	CreateTime time.Time `gorm:"column:create_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
	DeleleTime time.Time `gorm:"column:delele_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"delele_time"`
	DelState   int64     `gorm:"column:del_state;type:tinyint;not null" json:"del_state"`
	ProductID  int64     `gorm:"column:product_id;type:bigint;not null" json:"product_id"`
	Path       string    `gorm:"column:path;type:varchar(1024);not null;comment:图片路径" json:"path"`
	Type       int64     `gorm:"column:type;type:tinyint(1);not null;default:1;comment:图片存储类型：1-本地存储，2-七牛云存储" json:"type"`
	IsCover    int64     `gorm:"column:is_cover;type:tinyint(1);not null;comment:是否为商品封面图片" json:"is_cover"`
	ImgOrder   int64     `gorm:"column:img_order;type:tinyint(1);not null;comment:图片排序" json:"img_order"`
}

// TableName ProductImg's table name
func (*ProductImg) TableName() string {
	return TableNameProductImg
}
