// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProductStore = "product_store"

// ProductStore mapped from table <product_store>
type ProductStore struct {
	ID           int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	CreateTime   time.Time `gorm:"column:create_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime   time.Time `gorm:"column:update_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
	DeleleTime   time.Time `gorm:"column:delele_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"delele_time"`
	DelState     int64     `gorm:"column:del_state;type:tinyint;not null" json:"del_state"`
	Title        string    `gorm:"column:title;type:varchar(32);not null;comment:店铺名称" json:"title"`
	BossID       int64     `gorm:"column:boss_id;type:bigint;not null;index:ix_boss_id,priority:1;comment:店主用户id" json:"boss_id"`
	Introduction string    `gorm:"column:introduction;type:varchar(255);not null;comment:店铺介绍" json:"introduction"`
	State        int64     `gorm:"column:state;type:tinyint(1);not null;comment:0-禁止营业，1-正常营业" json:"state"`
	CollectNum   int64     `gorm:"column:collect_num;type:bigint;not null;comment:店铺收藏数" json:"collect_num"`
	Cover        string    `gorm:"column:cover;type:varchar(1024);not null;comment:封面图" json:"cover"`
}

// TableName ProductStore's table name
func (*ProductStore) TableName() string {
	return TableNameProductStore
}
