// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProductOperation = "product_operation"

// ProductOperation mapped from table <product_operation>
type ProductOperation struct {
	ID         int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	CreateTime time.Time `gorm:"column:create_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;type:datetime;not null;index:ix_update_time,priority:1;default:CURRENT_TIMESTAMP" json:"update_time"`
	DeleteTime time.Time `gorm:"column:delete_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"delete_time"`
	DelState   int64     `gorm:"column:del_state;type:tinyint;not null" json:"del_state"`
	ProductID  int64     `gorm:"column:product_id;type:bigint unsigned;not null;comment:商品id" json:"product_id"`
	Status     int64     `gorm:"column:status;type:int;not null;default:1;comment:运营商品状态 0-下线 1-上线" json:"status"`
}

// TableName ProductOperation's table name
func (*ProductOperation) TableName() string {
	return TableNameProductOperation
}
