// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameProduct = "product"

// Product mapped from table <product>
type Product struct {
	ID            int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	CreateTime    time.Time `gorm:"column:create_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime    time.Time `gorm:"column:update_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
	DeleleTime    time.Time `gorm:"column:delele_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"delele_time"`
	DelState      int64     `gorm:"column:del_state;type:tinyint;not null" json:"del_state"`
	Version       int64     `gorm:"column:version;type:bigint;not null;comment:乐观锁版本号" json:"version"`
	CategoryID    int64     `gorm:"column:category_id;type:bigint;not null;index:ix_category_id,priority:1;comment:商品所属分类id" json:"category_id"`
	Title         string    `gorm:"column:title;type:varchar(32);not null;comment:商品标题" json:"title"`
	SubTitle      string    `gorm:"column:sub_title;type:varchar(128);not null;comment:商品副标题" json:"sub_title"`
	Banner        string    `gorm:"column:banner;type:varchar(4096);not null;comment:商品轮播图，第一张图是封面，使用“，”区分每个图片地址" json:"banner"`
	Introduction  string    `gorm:"column:introduction;type:varchar(4096);not null;comment:商品介绍" json:"introduction"`
	Price         int64     `gorm:"column:price;type:bigint;not null;comment:商品价格（分）" json:"price"`
	DiscountPrice int64     `gorm:"column:discount_price;type:bigint;not null;comment:折扣价格（分）" json:"discount_price"`
	OnSale        int64     `gorm:"column:on_sale;type:tinyint(1);not null;comment:0-下架，1-上架售卖，2-缺货中" json:"on_sale"`
	Stock         int64     `gorm:"column:stock;type:bigint;not null;comment:库存" json:"stock"`
	SellCount     int64     `gorm:"column:sell_count;type:bigint;not null;comment:销售数量" json:"sell_count"`
	Score         int64     `gorm:"column:score;type:int unsigned;not null;comment:商品评分" json:"score"`
	CommentCount  int64     `gorm:"column:comment_count;type:int unsigned;not null;comment:评论数量" json:"comment_count"`
	StoreID       int64     `gorm:"column:store_id;type:bigint;not null;index:ix_store_id,priority:1;comment:店铺id" json:"store_id"`
	BossID        int64     `gorm:"column:boss_id;type:bigint;not null;comment:店主id" json:"boss_id"`
}

// TableName Product's table name
func (*Product) TableName() string {
	return TableNameProduct
}
