// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSeckillProduct = "seckill_product"

// SeckillProduct mapped from table <seckill_product>
type SeckillProduct struct {
	ID           int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	CreateTime   time.Time  `gorm:"column:create_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime   time.Time  `gorm:"column:update_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
	DeleleTime   time.Time  `gorm:"column:delele_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"delele_time"`
	DelState     int64      `gorm:"column:del_state;type:tinyint;not null" json:"del_state"`
	Version      int64      `gorm:"column:version;type:bigint;not null;comment:乐观锁版本号" json:"version"`
	ProductID    int64      `gorm:"column:product_id;type:bigint;not null;comment:参与秒杀的商品id" json:"product_id"`
	StoreID      int64      `gorm:"column:store_id;type:bigint;not null;comment:秒杀商品的店铺id" json:"store_id"`
	SeckillPrice int64      `gorm:"column:seckill_price;type:bigint;not null;comment:商品秒杀价格（分）" json:"seckill_price"`
	StockCount   int64      `gorm:"column:stock_count;type:int;not null;comment:秒杀商品的库存" json:"stock_count"`
	StartTime    *time.Time `gorm:"column:start_time;type:date;index:ix_time,priority:1;comment:秒杀开始日期（不包括具体时间）" json:"start_time"`
	Time         int64      `gorm:"column:time;type:int;not null;index:ix_time,priority:2;comment:秒杀开始的整点时间（时间为10，12，14）" json:"time"`
}

// TableName SeckillProduct's table name
func (*SeckillProduct) TableName() string {
	return TableNameSeckillProduct
}
