// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	order "zero-shop/order/api/internal/handler/order"
	"zero-shop/order/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CheckUserState},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/order/product",
					Handler: order.CreateProductOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/order/seckill",
					Handler: order.CreateSeckillOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/order/list",
					Handler: order.OrderListHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/order/detail",
					Handler: order.OrderDetailHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/order",
					Handler: order.DeleteOrderHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/order/v1"),
	)
}
