// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	cart "zero-shop/cart/api/internal/handler/cart"
	"zero-shop/cart/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CheckUserState},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/cart",
					Handler: cart.AddProductToCartHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/cart",
					Handler: cart.CartProductListHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/cart",
					Handler: cart.DeleteProductFromCartHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/cart",
					Handler: cart.UpdateProductDetailHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/cart/v1"),
	)
}
